####################################
# 创建者：环球在线
# 基于 Clash.Meta 内核 和 ACL4SSR_Online_Full.ini
# 创建时间：2024-08-08 12:49:15
# 节点类型：ss, vmess, ssr, trojan, http, socks5, hysteria, vless
####################################

mixed-port: 7890 # HTTP(S) 和 SOCKS 代理混合端口
# http-port: 7899 # HTTP(S) 代理端口
# socks-port: 7898 # SOCKS5 代理端口
# redir-port: 7891 # redirect 透明代理端口，仅能代理 TCP 流量，仅适用于 Linux 以及 macOS 使用
# tproxy-port: 1536 # tproxy 透明代理端口，可以代理 TCP 以及 UDP 流量，仅限 linux 适用 (Android 设备属于 Linux 设备）

mode: rule # 运行模式：rule 规则匹配；global 全局代理(需要在GLOBAL策略组选择代理/策略)；direct 全局直连
find-process-mode: strict # 进程匹配模式：always 开启，强制匹配所有进程；；strict 默认，由 Clash 判断是否开启；off 不匹配进程，推荐在路由器上使用此模式
global-client-fingerprint: random # 全局客户端指纹，可选："chrome", "firefox", "safari", "iOS", "android", "edge", "360"," qq", "random"；若选择 "random", 则按 Cloudflare Radar 数据按概率生成一个现代浏览器指纹。
global-ua: clash.meta # 自定义外部资源下载时使用的UA,默认为 clash.meta
log-level: error # 日志级别：silent 静默，不输出；error 仅输出发生错误至无法使用的日志；warning 输出发生错误但不影响运行的日志，以及 error 级别内容；info 输出一般运行的内容，以及 error 和 warning 级别的日志；debug 尽可能的输出运行中所有的信息
allow-lan: true # 允许局域网内其他设备经过 Clash 的代理端口访问互联网，可选值 true/false
bind-address: "*" # 绑定 IP, 通过 LAN 访问一个/一些特定的 IP 地址，"*" 绑定所有 IP 地址，默认值，不填写此项则绑定全部
ipv6: true # 是否允许内核接受 IPv6 流量，可选值 true/false
tcp-concurrent: true # tcp并发，允许同时处理多个tcp连接，可选值 true/false
keep-alive-interval: 30 # TCP Keep Alive 间隔,单位秒 | 控制 Clash 发出 TCP Keep Alive 包的间隔,减少移动设备耗电问题的临时措施
unified-delay: true # 统一延迟，更换延迟计算方式,去除握手等额外延迟 可选值 true/false

# GEO文件配置
geodata-mode: true # GeoIP 使用的文件,可选 true 为.dat/ false 为.mmdb
geosite-matcher: succinct # GeoSite 使用的匹配器实现，可选：succinct：与规则集相同；mph：来自 V2Ray，也是 Xray 中的“混合”
geodata-loader: memconservative # GEO 文件加载模式：standard：标准加载器；memconservative：专为内存受限(小内存)设备优化的加载器(默认值)
geo-auto-update: true # 自动更新 GEO 文件,可选 true/false
geo-update-interval: 144 # 更新间隔,单位：小时
geox-url: # 自定义 GEO 文件下载地址
  geoip: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://hub.gitmirror.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://hub.gitmirror.com/https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

profile: # 缓存
  store-selected: true # 储存 API 对策略组的选择，以供下次启动时使用
  store-fake-ip: true # 储存 fakeip 映射表，域名再次发生连接时，使用原有映射地址

sniffer: # 域名嗅器,通过读取握手包内的域名字段,将IP还原成域名,有效解决Mapping机制的短板
  enable: true
  force-dns-mapping: true # 对 redir-host 类型识别的流量进行强制嗅探
  parse-pure-ip: true # 对所有未获取到域名的流量进行强制嗅探
  override-destination: true # 是否使用嗅探结果作为实际访问,默认为 true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true # 可覆盖 sniffer.override-destination
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain: # 需要强制嗅探的域名（默认情况下只对IP进行嗅探）
    - "+.v2ex.com"
  skip-domain: # 需要跳过嗅探的域名。主要解决部分站点sni字段非域名，导致嗅探结果异常的问题，如米家设备
    - "Mijia Cloud"

dns:
  enable: true
  prefer-h3: true #优先使用 DOH 的 http/3
  listen: 0.0.0.0:1053
  ipv6: true
  ipv6-timeout: 300 #ipv6超时，单位 毫秒
  cache-algorithm: arc #缓存算法
  use-hosts: true #查询系统Hosts
  default-nameserver: #默认 DNS, 用于解析 DNS 服务器 的域名，必须为 IP, 可为加密 DNS
    - 223.5.5.5
    - 114.114.114.114
    - 119.29.29.29
  enhanced-mode: fake-ip # enhanced-mode可选 redir-host 和 fake-ip，fake-ip响应更快但可能带来一些问题
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: #fakeip 过滤，以下地址不会下发 fakeip 映射用于连接
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver-policy: ##指定域名查询的解析服务器，优先于 nameserver/fallback 查询
    "geosite:cn,private":
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver: #默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
    - https://8.8.8.8/dns-query  
    - https://1.0.0.1/dns-query
  proxy-server-nameserver: #代理节点域名解析服务器，仅用于解析代理节点的域名
    - https://doh.pub/dns-query
    - https://8.8.4.4/dns-query
    - https://1.0.0.1/dns-query
